### ISSUE TITLE
Larke Admin 截图预览

### ISSUE THREAD

**Issue by deatil** [deatil/larke-admin#1]
> 截图预览

![index](https://user-images.githubusercontent.com/24578855/101989891-51571580-3cde-11eb-8a6a-ec602d1eaf1c.png)

![admin](https://user-images.githubusercontent.com/24578855/101988564-6bd8c100-3cd5-11eb-8524-21151ba3b404.png)

![admin-access](https://user-images.githubusercontent.com/24578855/101989890-4e5c2500-3cde-11eb-8db3-3b79674f102e.jpg)

![attach](https://user-images.githubusercontent.com/24578855/101988566-6da28480-3cd5-11eb-9532-69d88b2f598d.png)

![config](https://user-images.githubusercontent.com/24578855/101988567-6e3b1b00-3cd5-11eb-8799-66e8ebec6020.png)

![extension](https://user-images.githubusercontent.com/24578855/101988568-6f6c4800-3cd5-11eb-845c-066d52ef7958.png)

![login](https://user-images.githubusercontent.com/24578855/101988572-71360b80-3cd5-11eb-9109-1e959f99663b.png)

![menus](https://user-images.githubusercontent.com/24578855/101988573-71cea200-3cd5-11eb-8e8b-e80ab319b216.png)

![roles](https://user-images.githubusercontent.com/24578855/101988575-72673880-3cd5-11eb-93c6-4f1e85cc597a.png)

![rule](https://user-images.githubusercontent.com/24578855/101988577-72ffcf00-3cd5-11eb-956c-37d3453689b1.png)

![setting](https://user-images.githubusercontent.com/24578855/101988579-73986580-3cd5-11eb-8bde-bc72185e5273.png)

![settings](https://user-images.githubusercontent.com/24578855/101988581-74c99280-3cd5-11eb-894b-06f2b25cacd9.jpg)

**Comment by deatil** [comment]
![admin-access](https://user-images.githubusercontent.com/24578855/102609135-f3a34d00-4165-11eb-87a9-c2d98eaca02a.png)

![rule2](https://user-images.githubusercontent.com/24578855/102609155-f9992e00-4165-11eb-93ad-82275af134ab.png)

**Comment by deatil** [comment]
![Uploading admin-access.png…]()

**Comment by deatil** [comment]
![admin-access](https://user-images.githubusercontent.com/24578855/103433753-db393500-4c31-11eb-8d8a-b40dfa0db84e.png)

**Comment by deatil** [comment]
![index](https://user-images.githubusercontent.com/24578855/103433805-aed1e880-4c32-11eb-8d5b-50638bfc13b5.png)

**Comment by deatil** [comment]
![login](https://user-images.githubusercontent.com/24578855/103483910-8cec8780-4e25-11eb-93c5-ea7ce7a09b60.png)

**Comment by deatil** [comment]
![index](https://user-images.githubusercontent.com/24578855/105568367-cacd3380-5d73-11eb-98ab-55701d0068ed.png)

**Comment by deatil** [comment]
![admin](https://github.com/deatil/larke-admin/assets/24578855/9d7d25dd-f346-4857-bb25-38b045a38ba4)
![admin](https://github.com/deatil/larke-admin/assets/24578855/ecb58b9e-97b7-4840-83b9-554abe5e8d69)

**Comment by git4coder** [comment]
不应该放到 wiki 么，怎么在 issue 里。。

**Comment by deatil** [comment]
> 不应该放到 wiki 么，怎么在 issue 里。。

没用wiki。readme 需要用到的图片只有上传的才能在国内能访问
该回复后面点会被删除，有问题可以提新的issue
