### ISSUE TITLE
怎样自己添加api呢？

### ISSUE THREAD

**Issue by moxixi527** [deatil/larke-admin#10]
我想要在后台中多写几个管理模块，写的过程中报错了，但是返回的数据是经过封装了的，无法看到报的是什么错，怎样才能看见这些错误呢？麻烦解答一下，谢谢

**Comment by deatil** [comment]
报错把laravel的调试打开。然后报错的话，返回的json数据里的data有报错信息，laravel的日志里也有报错的信息

**Comment by moxixi527** [comment]
已经把debug设置为true，然后如果报错的话，前台并没有看见任何的json数据，只有一个token未获取到的报错，laravel的日志里的报错信息很简短，无法得知具体的错误信息。麻烦您看一下，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月29日(星期三) 下午5:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [deatil/larke-admin] 怎样自己添加api呢？ (Issue #10)





 
报错把laravel的调试打开。然后报错的话，返回的json数据里的data有报错信息，laravel的日志里也有报错的信息
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by deatil** [comment]
能截图的话截个报错的图。开启调试后会返回抛出异常的具体报错信息，不是异常的报错的话只有相应的提示

**Comment by moxixi527** [comment]
我在上传头像图片时一直报错，经过排查发现attachment表的name字段长度太小，插入数据时会报错哦~




点开报错提示以后出现的效果是token不能为空，但事实上是我的model的class名写错了，token是有传回去的。期待您的回复，麻烦您了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月29日(星期三) 晚上10:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [deatil/larke-admin] 怎样自己添加api呢？ (Issue #10)





 
能截图的话截个报错的图。开启调试后会返回抛出异常的具体报错信息，不是异常的报错的话只有相应的提示
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by moxixi527** [comment]
如果状态为0时这里不能显示对应的内容哦~


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "deatil/larke-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月29日(星期三) 晚上10:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [deatil/larke-admin] 怎样自己添加api呢？ (Issue #10)





 
能截图的话截个报错的图。开启调试后会返回抛出异常的具体报错信息，不是异常的报错的话只有相应的提示
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by deatil** [comment]
> 如果状态为0时这里不能显示对应的内容哦~

你回复的两个都有图片吗？回复有图片的只能github上回复才行

**Comment by moxixi527** [comment]
那怎么处理呢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月30日(星期四) 下午5:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [deatil/larke-admin] 怎样自己添加api呢？ (Issue #10)





  
如果状态为0时这里不能显示对应的内容哦~
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "deatil/larke-admin" @.&gt;; 发送时间:&nbsp;2021年12月29日(星期三) 晚上10:03 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [deatil/larke-admin] 怎样自己添加api呢？ (Issue #10) 能截图的话截个报错的图。开启调试后会返回抛出异常的具体报错信息，不是异常的报错的话只有相应的提示 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
你回复的两个都有图片吗？回复有图片的只能github上回复才行
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by deatil** [comment]
你在github上传下图片吧

**Comment by moxixi527** [comment]
已经上传，麻烦您了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "deatil/larke-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月30日(星期四) 晚上6:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [deatil/larke-admin] 怎样自己添加api呢？ (Issue #10)





 
你在github上传下图片吧
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by moxixi527** [comment]
还有就是，更新完页面以后，表格没有自动刷新欸



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月31日(星期五) 中午12:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [deatil/larke-admin] 怎样自己添加api呢？ (Issue #10)





 
Closed #10.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by deatil** [comment]
表格目前没做自动刷新。有需要的话可以先自己处理下

**Comment by moxixi527** [comment]
好的，收到




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月31日(星期五) 下午5:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [deatil/larke-admin] 怎样自己添加api呢？ (Issue #10)





 
表格目前没做自动刷新。有需要的话可以先自己处理下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
