### ISSUE TITLE
关于错误调试和上传头像失败的问题

### ISSUE THREAD

**Issue by moxixi527** [deatil/larke-admin#11]
1.我的laravel已经打开了错误调试，但是出错以后返回的错误调试全部都是token 不能为空

![image](https://user-images.githubusercontent.com/61492796/147801040-38bcdad5-4fce-468e-8b1e-60aaaf21c5c5.png)
点击上面的错误提示链接以后的json数据都是：
![image](https://user-images.githubusercontent.com/61492796/147801070-282abcde-6567-454b-94c4-6d9df365851c.png)

2.上传头像时一直失败，检查以后发现attachment表的name字段长度太小了，可以改一下哦~
3.如果状态设置为禁用，也就是值为0时，页面是无法显示禁用图标按钮的，如图：
![image](https://user-images.githubusercontent.com/61492796/147801124-ec8f5e95-dc8c-4c89-bf20-a7e53072bd8e.png)

**Comment by deatil** [comment]
2的问题后面的版本修复

**Comment by deatil** [comment]
3的问题，是你自己写的页面吧。不显示的话，需要看vue和elementui的文档，查下是哪的问题

**Comment by deatil** [comment]
1的问题，可以看
https://github.com/deatil/larke-admin-logviewer
这个扩展，前端的接口使用那块。用自定义的请求方法需要加带token的请求头

**Comment by moxixi527** [comment]
事实上token有加上，我用的是你们封装的request



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月31日(星期五) 中午12:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [deatil/larke-admin] 关于错误调试和上传头像失败的问题 (Issue #11)





 
1的问题，可以看
 https://github.com/deatil/larke-admin-logviewer
 这个扩展，前端的接口使用那块。用自定义的请求方法需要加带token的请求头
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by moxixi527** [comment]
不是哦，是权限路由的详情界面，包括其他界面也是一样的效果




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月31日(星期五) 中午12:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [deatil/larke-admin] 关于错误调试和上传头像失败的问题 (Issue #11)





 
3的问题，是你自己写的页面吧。不显示的话，需要看vue和elementui的文档，查下是哪的问题
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by deatil** [comment]
> 事实上token有加上，我用的是你们封装的request
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月31日(星期五) 中午12:05 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [deatil/larke-admin] 关于错误调试和上传头像失败的问题 (Issue #11) 1的问题，可以看 https://github.com/deatil/larke-admin-logviewer 这个扩展，前端的接口使用那块。用自定义的请求方法需要加带token的请求头 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这种你需要看下请求的数据头有没有带上token
