### ISSUE TITLE
上传头像时会将图片存储到attachment表中，然后我取出图片时应该怎么操作呢？

### ISSUE THREAD

**Issue by moxixi527** [deatil/larke-admin#12]
上传头像时会将图片存储到attachment表中，然后我取出图片时应该怎么操作呢？

**Comment by deatil** [comment]
用的默认上传的话，可以用 https://github.com/deatil/larke-admin/blob/main/src/larke/admin/helper.php#L63 这个获取完整的显示地址

**Comment by deatil** [comment]
附件模型取数据，默认会加个url字段，该字段可以直接在线展示使用

**Comment by moxixi527** [comment]
使用leftJoin？可是好像没有自动加url字段欸



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月31日(星期五) 中午12:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [deatil/larke-admin] 上传头像时会将图片存储到attachment表中，然后我取出图片时应该怎么操作呢？ (Issue #12)





 
附件表取出，默认会加个url字段，该字段可以直接在线展示使用
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by deatil** [comment]
> 使用leftJoin？可是好像没有自动加url字段欸
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月31日(星期五) 中午12:09 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [deatil/larke-admin] 上传头像时会将图片存储到attachment表中，然后我取出图片时应该怎么操作呢？ (Issue #12) 附件表取出，默认会加个url字段，该字段可以直接在线展示使用 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

只能用模型才有。用其他表联查没有用到模型的话该说不会自动加

**Comment by moxixi527** [comment]
好吧，我知道了，我直接存了返回的链接哈哈哈哈哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月31日(星期五) 晚上6:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [deatil/larke-admin] 上传头像时会将图片存储到attachment表中，然后我取出图片时应该怎么操作呢？ (Issue #12)





  
使用leftJoin？可是好像没有自动加url字段欸
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年12月31日(星期五) 中午12:09 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [deatil/larke-admin] 上传头像时会将图片存储到attachment表中，然后我取出图片时应该怎么操作呢？ (Issue #12) 附件表取出，默认会加个url字段，该字段可以直接在线展示使用 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
只能用模型才有。用其他表联查没有用到模型的话该说不会自动加
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
