### ISSUE TITLE
后台返回$this->error后，前台函数使用.catch没办法捕获异常

### ISSUE THREAD

**Issue by moxixi527** [deatil/larke-admin#13]
我想要的效果是提示相关错误信息以后，我再对页面进行一些操作，但是使用.catch毫无反应，这是为什么呢
![image](https://user-images.githubusercontent.com/61492796/148155187-d496fdb1-b486-4c01-ae53-cb9cbc2d723c.png)
![image](https://user-images.githubusercontent.com/61492796/148155218-2db77a2e-b8e1-481c-a5fe-b062f4adaf42.png)
（没有打印任何东西）
盼回复，阿里嘎多

**Comment by moxixi527** [comment]
就算是console.log也不行

**Comment by moxixi527** [comment]
不好意思，蠢哭了，能catch,写错地方了

**Comment by deatil** [comment]
没问题就行

**Comment by moxixi527** [comment]
非常抱歉又来麻烦您了，我想请问一下，上传视频应该怎么处理呢？我request->file()一直是空，很苦恼。

**Comment by deatil** [comment]
完全一个视频像文件那样传，用图片的方法传就行。该说视频传的话需要分片什么的来传。搜的话就搜element视频上传，再加上后端laravel关键字

**Comment by moxixi527** [comment]
上传视频的时候报错了哦
![image](https://user-images.githubusercontent.com/61492796/148338093-b02f3c3d-f643-4c22-9329-d0b291c5a959.png)
然后我把service改了一下就可以了，
![image](https://user-images.githubusercontent.com/61492796/148338172-9303bd44-840f-4c62-9463-2b622a104ea0.png)
这样写是有什么特殊意义吗

**Comment by moxixi527** [comment]
![image](https://user-images.githubusercontent.com/61492796/148339646-7a95315b-cb9d-4734-ba21-834d3eaca34e.png)
或者这样也可以哈哈哈哈

**Comment by deatil** [comment]
> 上传视频的时候报错了哦 ![image](https://user-images.githubusercontent.com/61492796/148338093-b02f3c3d-f643-4c22-9329-d0b291c5a959.png) 然后我把service改了一下就可以了， ![image](https://user-images.githubusercontent.com/61492796/148338172-9303bd44-840f-4c62-9463-2b622a104ea0.png) 这样写是有什么特殊意义吗

这个主要拿来统计的，暂时没有啥意义

**Comment by deatil** [comment]
可以用那段注释的

**Comment by moxixi527** [comment]
感谢您的回复
还有一个问题，我把项目部署到服务器上面以后，访问不了图片这些资源了是怎么回事呢。要怎样处理这个问题啊

**Comment by deatil** [comment]
> 感谢您的回复 还有一个问题，我把项目部署到服务器上面以后，访问不了图片这些资源了是怎么回事呢。要怎样处理这个问题啊

服务器先删除旧的软连接，服务器再执行一次stroage的创建软连接命令。filesystems.php文件里有那个命令

**Comment by moxixi527** [comment]
！！！感谢
