### ISSUE TITLE
session配置为redis驱动 

### ISSUE THREAD

**Issue by llxbl** [deatil/larke-admin#14]
Target class [cache] does not exist.

**Comment by deatil** [comment]
admin没有用到session。

报这个错的话，该说是没有安装对应的redis包，redis对应的配置也需要配置

**Comment by llxbl** [comment]
env里正常配置，SESSION_DRIVER=redis 就报错 ，其它代码用redis是正常的呀。composer remove larke-admin这个包redis使用正常。

**Comment by llxbl** [comment]
config/larkeadmin.php 这份配置需要单独配置session？吗

**Comment by deatil** [comment]
larke-admin 没有用到session，也没有覆盖过session和redis的配置

**Comment by deatil** [comment]
估计得查下具体的具体的问题

**Comment by llxbl** [comment]
只要配置redis就这个错误，不使用larke-admin包的话一切正常，其它代码是正常使用。

**Comment by llxbl** [comment]
我再研究研究，谢谢回复 。

**Comment by deatil** [comment]
这个问题修复了。

admin 加载的顺序有点问题，更改了下顺序解决了这个问题

**Comment by llxbl** [comment]
感恩，昨天找到了这个问题但是家里连git有点儿费劲，哈哈看到邮件特意跑来公司感谢你哈哈。

**Comment by deatil** [comment]
[ok]
