### ISSUE TITLE
larkeadmin一直提示密码错误问题

### ISSUE THREAD

**Issue by lpz811** [deatil/larke-admin#16]
1、查看代码后    passport.php  login方法 中
     $prikey 一直不能从缓存中获取值  
  ```
  try {
            // 私钥
            **$prikey = Cache::get($prikeyCacheKey);**
            // 导入私钥
            $rsakey = PublicKeyLoader::load($prikey);
            // RSA 解出密码
            $password = $rsakey->withPadding(RSA::ENCRYPTION_PKCS1)
                ->decrypt($password);
        } catch(\Exception $e) {
            return $this->error(__('密码错误'), \ResponseCode::LOGIN_ERROR);
        }
```
2、
```
  // 监听事件
        event(new Event\PassportLoginBefore($request));
```
       监听事件中 在Listener 中不能找到对应的事件处理过程

**Comment by deatil** [comment]
输出的报错有截图吗？就是登陆后浏览器控制台那返回的报错的截图

**Comment by deatil** [comment]
缓存的话，需要确认下缓存的配置有没有对

是文件缓存的话确认下文件写入读取有没有权限

**Comment by deatil** [comment]
监听事件那个有报错截图吗

**Comment by lpz811** [comment]
1、登陆相应截图
![截图00](https://user-images.githubusercontent.com/14008842/153127641-bdc19cc8-c9bf-4c3d-83d8-6af352d1ea2d.png)
2、文件缓存在本地  file 驱动 ，配置是默认的，也正确
      环境搭建在windows上，是有权限的
3、监听事件PassportLoginBefore没有注册

**Comment by lpz811** [comment]
![Uploading 截图01.png…]()

**Comment by lpz811** [comment]
![截图01](https://user-images.githubusercontent.com/14008842/153128919-0dfe165a-696a-47ef-9c9e-cd181e80ff46.png)

**Comment by deatil** [comment]
headers那截个图看下，看起来像前端的包版本没有对

**Comment by lpz811** [comment]
![截图02](https://user-images.githubusercontent.com/14008842/153135911-c980120d-20a6-4e0d-9252-8d5edc54e5a8.png)
![截图03](https://user-images.githubusercontent.com/14008842/153135925-a94b4313-721a-4587-b49d-fd157e6ca155.png)

**Comment by lpz811** [comment]
大佬，这个是哪的问题啊 ，帮忙看下

> headers那截个图看下，看起来像前端的包版本没有对

大佬，这个是哪的问题啊 ，帮忙看下

**Comment by deatil** [comment]
> 大佬，这个是哪的问题啊 ，帮忙看下
> 
> > headers那截个图看下，看起来像前端的包版本没有对
> 
> 大佬，这个是哪的问题啊 ，帮忙看下

v1.2.1 版本修复了。

具体的就是跨域那块问题

默认配置没有加上 rsa 请求头字段，本地测试有在 env 加就没有发现这个问题

**Comment by lpz811** [comment]
> > 大佬，这个是哪的问题啊 ，帮忙看下
> > > headers那截个图看下，看起来像前端的包版本没有对
> > 
> > 
> > 大佬，这个是哪的问题啊 ，帮忙看下
> 
> v1.2.1 版本修复了。
> 
> 具体的就是跨域那块问题
> 
> 默认配置没有加上 rsa 请求头字段，本地测试有在 env 加就没有发现这个问题

我刚试了，感谢，升下级这个问题解决了
