### ISSUE TITLE
1.2 版本， /passport/captcha 的响应头没有暴露出来 Larke-Admin-Captcha-Id ，，导致 login 的时候带上的 Larke-Admin-Captcha-Id为undefined，导致登录不上

### ISSUE THREAD

**Issue by jiangniao1996** [deatil/larke-admin#17]

**Comment by deatil** [comment]
更新到1.2.1版本，默认配置文件需要重新推送一次覆盖旧的

**Comment by jiangniao1996** [comment]
然后又报说 frontend/roles not found 😗

**Comment by deatil** [comment]
> 然后又报说 frontend/roles not found 😗

前端库有安装吗？

**Comment by jiangniao1996** [comment]
有的，可以说一下按照你的思路来讲，是哪个前端库没安装导致的吗，我去对比一下

**Comment by deatil** [comment]
> 有的，可以说一下按照你的思路来讲，是哪个前端库没安装导致的吗，我去对比一下

就是适配的前端项目，提示没有就是前端项目没有安装成功。
这个 https://github.com/deatil/larke-admin-frontend 有按照文档安装吗

**Comment by deatil** [comment]
> 有的，可以说一下按照你的思路来讲，是哪个前端库没安装导致的吗，我去对比一下

not found 就是路由没有

**Comment by jiangniao1996** [comment]
![错误2](https://user-images.githubusercontent.com/37357277/153819061-e5477dcc-d755-4663-919e-ba45d57ceb29.png)


执行 php artisan larke-admin:import-route 时报这个错误

**Comment by deatil** [comment]
> ![错误2](https://user-images.githubusercontent.com/37357277/153819061-e5477dcc-d755-4663-919e-ba45d57ceb29.png)
> 
> 执行 php artisan larke-admin:import-route 时报这个错误

这个是你有自定义过路由吗？自定义的路由注释有些问题。
这个好像是个问题，需要优化下

**Comment by deatil** [comment]
测试的话先用纯净的laravel安装下看看先

**Comment by deatil** [comment]
拉下新版本试下

**Comment by jiangniao1996** [comment]
我们现在用的时1.1.25版本，现在不好升级了，只能暂时先用着这个版本，不然前端要改的地方很多。
现在的问题是这个版本 passport/captcha、passport/login 接口都能调用成功，但之后的 frontend/roles 显示 not found，关于这个你有什么思路吗？
![error](https://user-images.githubusercontent.com/37357277/153988400-e3660bc1-bea1-480a-bbff-48ef58a8f802.png)

**Comment by deatil** [comment]
> 我们现在用的时1.1.25版本，现在不好升级了，只能暂时先用着这个版本，不然前端要改的地方很多。 现在的问题是这个版本 passport/captcha、passport/login 接口都能调用成功，但之后的 frontend/roles 显示 not found，关于这个你有什么思路吗？ ![error](https://user-images.githubusercontent.com/37357277/153988400-e3660bc1-bea1-480a-bbff-48ef58a8f802.png)

前端包的路由文件没有加载上，路由丢失了。

然后，前端或者后端改得多以后不建议升级随版本升级
