### ISSUE TITLE
会适配laravel9吗？

### ISSUE THREAD

**Issue by zbage** [deatil/larke-admin#18]

**Comment by deatil** [comment]
会的

**Comment by zbage** [comment]
试了下laravel9 出错：

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Root composer.json requires lake/larke-admin ^1.2 -> satisfiable by lake/larke-admin[1.2.0, 1.2.1, 1.2.2, 1.2.3].
    - lake/larke-admin[1.2.0, ..., 1.2.3] require laravel/framework ^8.0 -> found laravel/framework[v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.2).

**Comment by deatil** [comment]
> 试了下laravel9 出错：
> 
> Your requirements could not be resolved to an installable set of packages. Problem 1 - Root composer.json requires lake/larke-admin ^1.2 -> satisfiable by lake/larke-admin[1.2.0, 1.2.1, 1.2.2, 1.2.3]. - lake/larke-admin[1.2.0, ..., 1.2.3] require laravel/framework ^8.0 -> found laravel/framework[v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.2).

laravel9还没有适配好

**Comment by deatil** [comment]
适配的差不多了，可以重新试下
