### ISSUE TITLE
前端试了几次都报错

### ISSUE THREAD

**Issue by Mario-Blockchain** [deatil/larke-admin#2]
前端试了几次都报错，大佬有联系方式吗

**Comment by deatil** [comment]
出现了什么问题？可以截图发出来看下

**Comment by Mario-Blockchain** [comment]
缺少一个js  你有联系方式吗  我截图

**Comment by deatil** [comment]
> 缺少一个js 你有联系方式吗 我截图

github可以直接上传图片的。拖到编辑框上传

**Comment by Mario-Blockchain** [comment]
现在在改 laravue 晚点

**Comment by Mario-Blockchain** [comment]
![image](https://user-images.githubusercontent.com/70246542/107171377-9d33eb80-69fd-11eb-8835-ac10814c28e5.png)
我的环境是homestead  顺便问一下后台路径是admin-api吗  我是新手

**Comment by deatil** [comment]
> ![image](https://user-images.githubusercontent.com/70246542/107171377-9d33eb80-69fd-11eb-8835-ac10814c28e5.png)
> 我的环境是homestead 顺便问一下后台路径是admin-api吗 我是新手

你这个是 `/src/extension` 文件夹没有了

api的后台路径是 `admin-api` 这个

**Comment by caizhuoyao** [comment]
我编译前端是在项目public/admin下编译还是public/admin/src/resource/assets下编译

**Comment by Mario-Blockchain** [comment]
是没有这个目录  这个文件是在src/utils下面啊  我直接在admin下面编译的

**Comment by deatil** [comment]
> 是没有这个目录 这个文件是在src/utils下面啊 我直接在admin下面编译的

那个文件是在的也没问题。报错是因为没有 `/src/extension` 这个目录。
你安装后是没有这个目录的吗

**Comment by Mario-Blockchain** [comment]
安装后没有这个目录，我刚从git上克隆了一个下来

**Comment by deatil** [comment]
> 安装后没有这个目录，我刚从git上克隆了一个下来

我说的是安装后编译的目录。
你把编译的目录加上extension文件夹再试下

**Comment by Mario-Blockchain** [comment]
![image](https://user-images.githubusercontent.com/70246542/107175675-66af9e00-6a08-11eb-9b26-c1bc9df76426.png)
![image](https://user-images.githubusercontent.com/70246542/107175695-74652380-6a08-11eb-9b0e-c007bf745451.png)
后台报错404

**Comment by Mario-Blockchain** [comment]
大佬 能看出哪里的问题吗

**Comment by deatil** [comment]
> ![image](https://user-images.githubusercontent.com/70246542/107175675-66af9e00-6a08-11eb-9b26-c1bc9df76426.png)
> ![image](https://user-images.githubusercontent.com/70246542/107175695-74652380-6a08-11eb-9b0e-c007bf745451.png)
> 后台报错404

服务端的看起来没有安装成功

**Comment by deatil** [comment]
还有个可能就是你用的环境，composer安装后会少文件。

开发环境没有用 `homestead`，具体的情况需要你比对下代码看看没有缺失的文件

**Comment by Mario-Blockchain** [comment]
![image](https://user-images.githubusercontent.com/70246542/107181002-f22f2c00-6a14-11eb-8844-4de3491f744e.png)
![image](https://user-images.githubusercontent.com/70246542/107181020-f9563a00-6a14-11eb-936b-57ba506d854f.png)
直接用虚拟机主机访问9527端口 前端好像是起来了   但是和后端通信有问题

**Comment by Mario-Blockchain** [comment]
![image](https://user-images.githubusercontent.com/70246542/107181311-84cfcb00-6a15-11eb-9608-1a4d1be2477a.png)
服务端应该是起来的了   但是不知道为什么前后端不能通信

**Comment by deatil** [comment]
> ![image](https://user-images.githubusercontent.com/70246542/107181311-84cfcb00-6a15-11eb-9608-1a4d1be2477a.png)
> 服务端应该是起来的了 但是不知道为什么前后端不能通信

你看下你的服务端的代码的路由文件是不是存在

**Comment by Mario-Blockchain** [comment]
![image](https://user-images.githubusercontent.com/70246542/107182751-4be52580-6a18-11eb-934b-841ccaa13281.png)
原先没有这个路由文件  刚刚手动添加的

**Comment by Mario-Blockchain** [comment]
大佬可以付费帮忙解决一下问题吗

**Comment by Mario-Blockchain** [comment]
终于弄好了  大佬什么时候更新库，之前是跨域问题
![image](https://user-images.githubusercontent.com/70246542/107200697-fec27d00-6a32-11eb-9f72-05475be7a892.png)
![image](https://user-images.githubusercontent.com/70246542/107200722-071ab800-6a33-11eb-825d-a41c57ae35ac.png)
这里少了路径  导致没法访问加进去就好了

**Comment by deatil** [comment]
> 终于弄好了 大佬什么时候更新库，之前是跨域问题
> ![image](https://user-images.githubusercontent.com/70246542/107200697-fec27d00-6a32-11eb-9f72-05475be7a892.png)
> ![image](https://user-images.githubusercontent.com/70246542/107200722-071ab800-6a33-11eb-825d-a41c57ae35ac.png)
> 这里少了路径 导致没法访问加进去就好了

你安装的版本有点奇怪，这是很久前的版本，还没有在系统内处理跨域的问题。

新版本已经处理了跨域问题

**Comment by Mario-Blockchain** [comment]
我就是github上直接拉取的  你更新库了吗

**Comment by deatil** [comment]
> 我就是github上直接拉取的 你更新库了吗

那你拉取的好像不是最新的

**Comment by Mario-Blockchain** [comment]
晚上再拉取试试看 是我安装有问题吗？我先git clone 后端 发布 然后git前端编译打包

**Comment by deatil** [comment]
> 晚上再拉取试试看 是我安装有问题吗？我先git clone 后端 发布 然后git前端编译打包

没问题
