### ISSUE TITLE
[Feature]: 您好 前后端 已经运行起来了 但是要进行二次开发 如何进行

### ISSUE THREAD

**Issue by people-sea** [deatil/larke-admin#20]
### 功能描述以及必要性描述

您好 前后端 已经运行起来了 但是要进行二次开发 如何进行

### 建议和方案

您好 前后端 已经运行起来了 但是要进行二次开发 如何进行

**Comment by deatil** [comment]
扩展后台的话，推荐以扩展方式开发，方便分模块。

有覆盖已有路由需求的话，根据laravel路由覆盖方法覆盖来替换已有路由

**Comment by people-sea** [comment]
好的谢谢
