### ISSUE TITLE
下载zip 拓展 (deatil / larke-operation-log) 上传成功后 调用/admin-api/extension/local 报错

### ISSUE THREAD

**Issue by people-sea** [deatil/larke-admin#21]
### larke-admin 版本

1.3.3

### php 版本

7.4

### Laravel 版本

8

### 是否依旧存在

可以

### bug描述

1下载zip 拓展 (deatil / larke-operation-log) 
2上传成功后
3 本地拓展->拓展管理->安装/更新  (调用/admin-api/extension/local 报错)
`[2022-05-12 14:29:32] local.ERROR: Method Larke\Admin\OperationLog\ServiceProvider::withExtensionFromComposer does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method Larke\\Admin\\OperationLog\\ServiceProvider::withExtensionFromComposer does not exist. at /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113)
[stacktrace]`

**Comment by deatil** [comment]
larke-admin 版本没对，需要最新版的

系统最新版的php需要8以上

**Comment by people-sea** [comment]
laravel 版本呢

**Comment by deatil** [comment]
> laravel 版本呢

1.3.5，用最新的吧

**Comment by people-sea** [comment]
自行开发 按照拓展方式  不用 发布 composer上吧

**Comment by deatil** [comment]
> 自行开发 按照拓展方式 不用 发布 composer上吧

放扩展目录不用发布，直接就可以安装使用

**Comment by people-sea** [comment]
谢谢
