### ISSUE TITLE
[Bug]: 登录后显示请设置适配菜单后登陆系统

### ISSUE THREAD

**Issue by slarksnake** [deatil/larke-admin#23]
### larke-admin 版本

1.3.9

### php 版本

php8.1.4

### Laravel 版本

laravel9

### 是否依旧存在

可以

### bug描述

<img width="522" alt="image" src="https://user-images.githubusercontent.com/11405082/190861914-5765405f-eb27-4f57-948d-6f1f97b83359.png">
登录成功之后显示需要设置菜单

<img width="996" alt="image" src="https://user-images.githubusercontent.com/11405082/190862002-bc339d4c-1933-451c-a288-695f35e6e5fc.png">
数据库的表中只有admin和config有数据是否是缺少数据

### 修改建议

env中设置了DB_PREFIX=  不生效

**Comment by deatil** [comment]
安装步骤的第四步需要执行导入权限信息

**Comment by slarksnake** [comment]
是个全新的空项目所以还没有权限信息

**Comment by deatil** [comment]
> 是个全新的空项目所以还没有权限信息

系统默认安装，权限信息也是需要先导入的。需要执行权限导入命令，默认是没有权限数据的

**Comment by slarksnake** [comment]
php artisan larke-admin:import-route
那除了这个以外是否还有别的需要执行呢？

**Comment by deatil** [comment]
> php artisan larke-admin:import-route 那除了这个以外是否还有别的需要执行呢？

还有推送配置文件
