### ISSUE TITLE
怎么打开后台的管理地址啊，路由是什么啊[Question]: 

### ISSUE THREAD

**Issue by wentiangang** [deatil/larke-admin#24]
### 疑惑的地方

怎么打开后台的管理地址啊，路由是什么啊

### 期望的结果

告诉一个访问后台的路由

**Comment by deatil** [comment]
需要前端编译，前端编译后就会自动进入登陆页面的。这个项目是只有api

**Comment by deatil** [comment]
接口可以看这里 https://github.com/deatil/larke-admin/tree/main/docs/api

**Comment by deatil** [comment]
前端代码 https://github.com/deatil/larke-admin-frontend

**Comment by deatil** [comment]
合在一起的只有thinkphp版的，可以看这个https://github.com/deatil/laket-admin
