### ISSUE TITLE
[Question]: 方法提示未定义

### ISSUE THREAD

**Issue by declandragon** [deatil/larke-admin#27]
### 疑惑的地方

```
"php": "^8.0",
"lake/larke-admin": "1.5.2",
```

app/Admin/routes.php 这个文件，找不到 routes 方法，ide 是 PhpStorm ，使用了 Laravel Idea 插件。
请问是实现的哪个方法，想用注解的方式标注一下，类似下面这种。
有点强迫症想处理一下，谢谢。

```
/**
* @method static \Illuminate\Routing\Route get(string $uri, array|string|callable|null $action = null)
*/
```

![image](https://github.com/deatil/larke-admin/assets/37643710/5da4b7ff-a523-4561-a5a3-de5dc246f088)

### 期望的结果

能直接跳转到方法定义的地方

**Comment by deatil** [comment]
https://github.com/deatil/larke-admin/blob/main/src/larke/admin/Extension/Manager.php#L274

截图里的是用的上面这个方法
