### ISSUE TITLE
[Question]: 怎么吧你的路由加载进来啊

### ISSUE THREAD

**Issue by jasonccs** [deatil/larke-admin#28]
### 疑惑的地方

我启动项目 ,然后访问你的 路由 http://localhost:8000/passport/captcha   http://localhost:8000/passport/passkey
都是404 找不到啊。 

### 期望的结果

怎么吧你的路由加载进来啊

**Comment by deatil** [comment]
默认路由是 /admin-api/passport/captcha ，如果没有分组前缀，那估计是设置文件没有对

**Comment by jasonccs** [comment]
这是来自QQ邮箱的假期自动回复邮件！
    您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，第一时间给您回复。

**Comment by deatil** [comment]
就是第二个安装步骤的三个文件更改名字需要更改下

**Comment by jasonccs** [comment]
![image](https://github.com/deatil/larke-admin/assets/17975766/0bb803f5-cd00-4d43-af82-5aac068fc665)
![image](https://github.com/deatil/larke-admin/assets/17975766/e9978189-2515-437c-934d-108b97fa3912)
![image](https://github.com/deatil/larke-admin/assets/17975766/da8efda0-6010-4ff3-85e2-20d388885b22)

            
 // RSA 解出密码
php8.2   $rsakey = PublicKeyLoader::load($prikey);
            $password = $rsakey->withPadding(RSA::ENCRYPTION_PKCS1)
                ->decrypt($password); 出现密码错误。

**Comment by deatil** [comment]
laravel 的 cache 你需要设置下，看是用redis还是用file，看截图是cache数据读取失败了

**Comment by jasonccs** [comment]
这个问题解决了，又有一个新的问题。
![image](https://github.com/deatil/larke-admin/assets/17975766/d70865f6-8dbb-4329-bc20-c5209e79041c)
![image](https://github.com/deatil/larke-admin/assets/17975766/7d709da0-b6a5-494b-be4a-d0fb795ed7fb)
Larke\Admin\LogViewer\Support\LogViewer 时区无法设置为 东八区啊，时间还是默认的UTC ， 提供一个通道配置设置时区;

**Comment by jasonccs** [comment]
> laravel 的 cache 你需要设置下，看是用redis还是用file，看截图是cache数据读取失败了
已解决

**Comment by deatil** [comment]
> 这个问题解决了，又有一个新的问题。 ![image](https://user-images.githubusercontent.com/17975766/262534265-d70865f6-8dbb-4329-bc20-c5209e79041c.png) ![image](https://user-images.githubusercontent.com/17975766/262534705-7d709da0-b6a5-494b-be4a-d0fb795ed7fb.png) Larke\Admin\LogViewer\Support\LogViewer 时区无法设置为 东八区啊，时间还是默认的UTC ， 提供一个通道配置设置时区;

这个用laravel默认的，你需要重新配置下laravel的时区为东八区的就行。时区是shanghai后缀的那个

**Comment by jasonccs** [comment]
laravel 配置的上海的 ，但是还是没有作用啊

**Comment by deatil** [comment]
> laravel 配置的上海的 ，但是还是没有作用啊

你先直接查看下文件的修改日期是不是正常的

**Comment by jasonccs** [comment]
文件日期是正确的
&nbsp;


风起时，想你
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月23日(星期三) 中午11:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [deatil/larke-admin] [Question]: 怎么吧你的路由加载进来啊 (Issue #28)





  
laravel 配置的上海的 ，但是还是没有作用啊
  
你先直接查看下文件的修改日期是不是正常的

**Comment by jasonccs** [comment]
![image](https://github.com/deatil/larke-admin/assets/17975766/22cd8670-0031-4df1-bcdb-df1d70899f2f)
文件日期是正确的

**Comment by deatil** [comment]
> ![image](https://user-images.githubusercontent.com/17975766/262540174-22cd8670-0031-4df1-bcdb-df1d70899f2f.png) 文件日期是正确的

是win下的话，直接进文件夹用右键看属性。都是对的那就只有更新文件日期的时候有问题了

**Comment by jasonccs** [comment]
![image](https://github.com/deatil/larke-admin/assets/17975766/7c87ba90-e2bc-40f3-962b-0b1fa44a774d)
windows 没有问题。我打印了，就是设置时区了但无效，你的无法加载时区，

**Comment by deatil** [comment]
> ![image](https://user-images.githubusercontent.com/17975766/262542032-7c87ba90-e2bc-40f3-962b-0b1fa44a774d.png) windows 没有问题。我打印了，就是设置时区了但无效，你的无法加载时区，

这个看了下原来的截图，也是有问题。这个后面我检查下。你可以暂时先自己修改成正确的时区

**Comment by jasonccs** [comment]
直接跟随 复制laralvel config 设置的时区。

**Comment by deatil** [comment]
时间格式化有点问题，后面版本我修复下

**Comment by deatil** [comment]
日期问题已经修复了
