### ISSUE TITLE
[Bug]: 我这个环境搭建好了，能到登录页面，为什么老提示密码错误？ 账户密码 admin/123456。这个一直提示错误

### ISSUE THREAD

**Issue by jinxu96** [deatil/larke-admin#29]
### larke-admin 版本

1.6.9

### php 版本

php 8.1

### Laravel 版本

laravel10

### 是否依旧存在

可以

### bug描述

1.安装后，登录一直password error
 2.\ResponseCode::LOGIN_ERROR，像这种，ResponseCode这个是不是扩展，我编辑器全局搜索LOGIN_ERROR，找不到

### 修改建议

1111111111

**Comment by jinxu96** [comment]
$password = $request->input('password');
        if (strlen($password) <= 16) {
            return $this->error(__('密码错误'), \ResponseCode::LOGIN_ERROR);
        }
这个判断有问题

**Comment by deatil** [comment]
ResponseCode 是加载的时候做的别名。
报错可以先看下错误日志

**Comment by jinxu96** [comment]
我在登陆的时候提示登陆失败，然后日志中打印出来的数据是 [2023-06-17 09:10:00] local.ERROR: larke-admin-jwt-makeToken: Object of class DateTimeImmutable could not be converted to int
[2023-06-17 09:10:00] local.ERROR: larke-admin-login: JWT编码失败

**Comment by jinxu96** [comment]
如果改了app.php配置，'timezone' => 'UTC',为PRC，则会报local.ERROR: larke-admin-login: Unable to read key这个错误

**Comment by deatil** [comment]
> 我在登陆的时候提示登陆失败，然后日志中打印出来的数据是 [2023-06-17 09:10:00] local.ERROR: larke-admin-jwt-makeToken: Object of class DateTimeImmutable could not be converted to int [2023-06-17 09:10:00] local.ERROR: larke-admin-login: JWT编码失败

这个报错是jwt的库下载的版本有问题，你看下composer下载的jwt的库版本是不是最新的。
通常这个问题是用的composer源有问题，可以先换个源或者用默认源

**Comment by deatil** [comment]
admin的版本你下载的好像不是最新的版本，可以先确认下php版本和composer列出的admin版本是不是最新的，不是最新的就有可能出现问题

**Comment by jinxu96** [comment]
"require": {
        "php": "^8.1",
        "lake/larke-admin": "^1.6.3",
    },
另外在composer.json文件中没有找到jwt

**Comment by deatil** [comment]
> ```
> "require": {
>     "php": "^8.1",
>     "lake/larke-admin": "^1.6.3",
> },
> ```
> 
> 另外在composer.json文件中没有找到jwt

你需要在命令行用compser命令列出包的版本看。或者先换个源重新更新拉取下，怀疑现在用的源有问题

**Comment by jinxu96** [comment]
lake/larke-admin                   1.6.3     An admin api library with JWT and RBAC.
lake/larke-auth                    1.3.0     An authorization library that supports access control models like ACL, RBAC, ABAC in Laravel.
lake/larke-jwt                     1.1.6     A library to work with JSON Web Token and JSON Web Signature.

**Comment by deatil** [comment]
> lake/larke-admin 1.6.3 An admin api library with JWT and RBAC. lake/larke-auth 1.3.0 An authorization library that supports access control models like ACL, RBAC, ABAC in Laravel. lake/larke-jwt 1.1.6 A library to work with JSON Web Token and JSON Web Signature.

那就不是最新的版本。换composer源试下

**Comment by jinxu96** [comment]
好了，得换腾讯源，要指定 composer require lake/larke-admin 1.6.9

**Comment by jinxu96** [comment]
前端页面在左侧增加菜单，需要怎么做呀

**Comment by deatil** [comment]
> 前端页面在左侧增加菜单，需要怎么做呀

手动在路由里添加，需要授权的菜单在后台授权后就会显示。
可以下载一个扩展插件，看下扩展的逻辑

**Comment by deatil** [comment]
前端开发可以看 vue-element-admin 文档

**Comment by jinxu96** [comment]
> > 前端页面在左侧增加菜单，需要怎么做呀
> 
> 手动在路由里添加，需要授权的菜单在后台授权后就会显示。 可以下载一个扩展插件，看下扩展的逻辑

我加加菜单，就要写一个扩展么

**Comment by deatil** [comment]
> > > 前端页面在左侧增加菜单，需要怎么做呀
> > 
> > 
> > 手动在路由里添加，需要授权的菜单在后台授权后就会显示。 可以下载一个扩展插件，看下扩展的逻辑
> 
> 我加加菜单，就要写一个扩展么

可以根据 vue-element-admin 文档来。用扩展是为了解藕，更新方便些

**Comment by jinxu96** [comment]
还有就是，我通过postman访问登录接口，会出现"message": "password error"，通过网站登录就可以登录成功，

**Comment by deatil** [comment]
> 还有就是，我通过postman访问登录接口，会出现"message": "password error"，通过网站登录就可以登录成功，

网页有用rsa加密密码的，用postman也需要加密

**Comment by jinxu96** [comment]
> > 还有就是，我通过postman访问登录接口，会出现"message": "password error"，通过网站登录就可以登录成功，
> 
> 网页有用rsa加密密码的，用postman也需要加密

`//Pre-request Script
//--------------以下为需要加密的内容，可以根据需求定义多个------------------//
var clearText = '123456';   //对应{{rsaBody}}的明文
// var clearText = '{"arg1":"def","arg2":123,"arg3":7.89}';

//---------------------------------------------------------------------//
const encrypt_key = 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDRHuh7yscqNGDJolwLsyAt0yAsslRi62dfKp7oIn99KCvq1jzXriimWJ1YMsNnW4fDnyX7bH+JzRsh8XNObCAFe3CWoMp0BozRnMlx3jivd5mz+koMuu49+386dog5H54cwhE+vqf756//yrSoIk4T40zV3aeE2CpKSTXPQVWJIQIDAQAB';
const forge_url = 'https://lzq1357.gitee.io/various/forge_min.js';
//forge_min.js来自：https://raw.githubusercontent.com/loveiset/RSAForPostman/master/forge.js
//---------------------------------------------------------------------//

function encryptRsa(encrypt_key, clearText){
    console.info('cleartext: ' + clearText);
    //注意此处上下的BEGIN PRIVATE KEY不要删除，框架自带的
    const public_key = '-----BEGIN PUBLIC KEY-----\n'
            + encrypt_key
            + '\n-----END PUBLIC KEY-----';
    var publicKey = forge.pki.publicKeyFromPem(public_key);
    var buffer = forge.util.createBuffer(clearText, 'utf8');
    var bytes = buffer.getBytes();
    var encryptedText = forge.util.encode64( publicKey.encrypt(bytes, 'RSAES-PKCS1-V1_5', {
            md: forge.md.sha256.create(),
            mgf1: {
                md: forge.md.sha1.create()
            }
        })
    );
    console.info('encryptedText: '+ encryptedText);
    return encryptedText;
};

// 第一次运行时从网络加载forgeJS，会导致请求失败
if(!pm.globals.has('forgeJS')){
    console.log('request forge.js from ' + forge_url);
    pm.sendRequest(forge_url, function (err, res) {
            if (err) {
                console.error(err);
            } else {
                console.info("request forgs.js: Succeed, please try again");
                //注意：Pre-request Script中出现报错，可能会导致pm.globals.set失效
                pm.globals.set('forgeJS', res.text());
            }
        }
    );
    return;
}
eval(pm.globals.get('forgeJS'));

//------------------以下内容根据需要修改定义，可以加密多个字段------------------------//
var encryptedText = encryptRsa(encrypt_key, clearText);
postman.setEnvironmentVariable("rsaBody", encryptedText);     //rsaBody对应Body中{{}}`我加密了，还是不行

**Comment by jinxu96** [comment]
try {
            // 私钥
            $prikey = Cache::get($prikeyCacheKey);
            dd($prikey); //打印为空
            // 导入私钥
            $rsakey = PublicKeyLoader::load($prikey);

            // RSA 解出密码
            $password = $rsakey->withPadding(RSA::ENCRYPTION_PKCS1)
                ->decrypt($password);

私钥打印为空

**Comment by deatil** [comment]
> try { // 私钥 $prikey = Cache::get($prikeyCacheKey); dd($prikey); //打印为空 // 导入私钥 $rsakey = PublicKeyLoader::load($prikey);
> 
> ```
>         // RSA 解出密码
>         $password = $rsakey->withPadding(RSA::ENCRYPTION_PKCS1)
>             ->decrypt($password);
> ```
> 
> 私钥打印为空

每次点击登录都需要请求获取一次公钥，请求登录的时候在控制台查看需要带的数据

**Comment by deatil** [comment]
postmam测试的话，在网页端拿取access_token来直接用好些

**Comment by jinxu96** [comment]
我试过，报token过期错误

**Comment by deatil** [comment]
可以看登录的文档 https://github.com/deatil/larke-admin/blob/main/docs/api/passport.md

**Comment by jinxu96** [comment]
> postmam测试的话，在网页端拿取access_token来直接用好些


我试过，报token过期错误

**Comment by deatil** [comment]
> > postmam测试的话，在网页端拿取access_token来直接用好些
> 
> 我试过，报token过期错误

测试把这里设置为空后再获取token来用 https://github.com/deatil/larke-admin/blob/main/src/larke/resources/config/larkeadmin.php#L61

**Comment by jinxu96** [comment]
'aud'    => env('LARKE_ADMIN_JWT_AUD', ''),设置为空了，然后拿到网页端的access_token，请求头部：

1. Locale-Language： zh_CN
2. Content-Type ： application/json;charset=utf-8
3. Authorization ： Bearer xxxx
还是不行

**Comment by jinxu96** [comment]
prikeyCacheKey + rsa(md5(password))这是是Larke-Admin-Passkey-Id头部的值和rsa(md5(password))的值拼接是吧，我现在`        try {
            // 私钥
            $prikey = Cache::get($prikeyCacheKey);

            // 导入私钥
            $rsakey = PublicKeyLoader::load($prikey);

            // RSA 解出密码
            $password = $rsakey->withPadding(RSA::ENCRYPTION_PKCS1)
                ->decrypt($password);
        } catch(\Exception $e) {
            Log::error('larke-admin-login: ' . $e->getMessage());

            return $this->error(__('密码错误'), \ResponseCode::LOGIN_ERROR);
        }

        $encryptPassword = AdminModel::checkPassword($adminInfo, $password);
        dd($adminInfo,$password);`
这个$password打印是空的

**Comment by jinxu96** [comment]
成功了，在线rsa加密顺序不对，感谢

**Comment by jinxu96** [comment]
我在前端页面配置了路由权限，给了分组路由权限，但是访问接口，没有访问权限

**Comment by deatil** [comment]
> 我在前端页面配置了路由权限，给了分组路由权限，但是访问接口，没有访问权限

需要在页面点击 更新权限缓存 才行

**Comment by jinxu96** [comment]
> > 我在前端页面配置了路由权限，给了分组路由权限，但是访问接口，没有访问权限
> 
> 需要在页面点击 更新权限缓存 才行
好的

**Comment by jinxu96** [comment]
`    # 后端静态资源处理
    location  ^~ /vendor/ {
        alias /path/public/vendor/;
    }
    location  ^~ /storage/ {
        alias /path/public/storage/;
    }`  ,部署项目的话，这个/path/public/vendor/是什么意思，是只需要换掉path就行吗，比如wwwroot/larke-admin/public/vendor/么

**Comment by deatil** [comment]
> ` # 后端静态资源处理 location ^~ /vendor/ { alias /path/public/vendor/; } location ^~ /storage/ { alias /path/public/storage/; }` ,部署项目的话，这个/path/public/vendor/是什么意思，是只需要换掉path就行吗，比如wwwroot/larke-admin/public/vendor/么

是的。更改path到绝对路径。laravel的安装需要把资源链接的脚本跑一次

**Comment by jinxu96** [comment]
比如自己创建了laravel项目叫test，然后composer引入你的扩展，照那个部署的话，test/public下没有vendor和srorage目录，只有test/vendor和test/storage，然后这个**laravel的安装需要把资源链接的脚本跑一次**是什么意思

**Comment by deatil** [comment]
> 比如自己创建了laravel项目叫test，然后composer引入你的扩展，照那个部署的话，test/public下没有vendor和srorage目录，只有test/vendor和test/storage，然后这个**laravel的安装需要把资源链接的脚本跑一次**是什么意思

那个文档只是示列，头像资源只用到了 srorage 这个目录。
就是需要把srorage的原始目录软链接到public目录。
那个脚本你可以看下laravel文档

**Comment by jinxu96** [comment]
我现在是www/wwwroot下有一个laravel的文件夹和前端的dist文件夹，然后我按你的配置，浏览器访问空白，几个css，js文件找不到，我看路径是对的

**Comment by deatil** [comment]
> 我现在是www/wwwroot下有一个laravel的文件夹和前端的dist文件夹，然后我按你的配置，浏览器访问空白，几个css，js文件找不到，我看路径是对的

前端的打包文件，大多都需要用代理到/根目录，api接口单独做个代理。哪些css和js不能访问？

**Comment by deatil** [comment]
部署，可以看这个文档 https://github.com/deatil/lakego-admin/blob/main/docs/nginx.md

**Comment by jinxu96** [comment]
我现在是这样的，登录页可以出来了，但是验证码刷不出来，然后我看network调的是这个http://mimeng.admin.com/stage-api/passport/passkey接口，这个接口响应200但是没有任何返回信息，
http://mimeng.admin.com:9527/admin-api/passport/passkey这个是我直接拿出来访问的，是由信息返回的，然后前端.env.production和.env.dev的配置都是这个VUE_APP_BASE_API = 'http://mimeng.admin.com:9527/admin-api/'，也换成过VUE_APP_BASE_API = 'http://mimeng.admin.com/admin-api/',但是都不行

**Comment by deatil** [comment]
> 我现在是这样的，登录页可以出来了，但是验证码刷不出来，然后我看network调的是这个[http://mimeng.admin.com/stage-api/passport/passkey接口，这个接口响应200但是没有任何返回信息，](http://mimeng.admin.com/stage-api/passport/passkey%E6%8E%A5%E5%8F%A3%EF%BC%8C%E8%BF%99%E4%B8%AA%E6%8E%A5%E5%8F%A3%E5%93%8D%E5%BA%94200%E4%BD%86%E6%98%AF%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E8%BF%94%E5%9B%9E%E4%BF%A1%E6%81%AF%EF%BC%8C) [http://mimeng.admin.com:9527/admin-api/passport/passkey这个是我直接拿出来访问的，是由信息返回的，然后前端.env.production和.env.dev的配置都是这个VUE_APP_BASE_API](http://mimeng.admin.com:9527/admin-api/passport/passkey%E8%BF%99%E4%B8%AA%E6%98%AF%E6%88%91%E7%9B%B4%E6%8E%A5%E6%8B%BF%E5%87%BA%E6%9D%A5%E8%AE%BF%E9%97%AE%E7%9A%84%EF%BC%8C%E6%98%AF%E7%94%B1%E4%BF%A1%E6%81%AF%E8%BF%94%E5%9B%9E%E7%9A%84%EF%BC%8C%E7%84%B6%E5%90%8E%E5%89%8D%E7%AB%AF.env.production%E5%92%8C.env.dev%E7%9A%84%E9%85%8D%E7%BD%AE%E9%83%BD%E6%98%AF%E8%BF%99%E4%B8%AAVUE_APP_BASE_API) = '[http://mimeng.admin.com:9527/admin-api/'，也换成过VUE_APP_BASE_API](http://mimeng.admin.com:9527/admin-api/'%EF%BC%8C%E4%B9%9F%E6%8D%A2%E6%88%90%E8%BF%87VUE_APP_BASE_API) = '[http://mimeng.admin.com/admin-api/',但是都不行](http://mimeng.admin.com/admin-api/',%E4%BD%86%E6%98%AF%E9%83%BD%E4%B8%8D%E8%A1%8C)

你需要看具体的请求链接，链接直接请求没有问题，那基本就是没啥问题。主要就是看web请求了

**Comment by jinxu96** [comment]
`http://admin.xiijq.cn/`,这个可以直接访问的，

**Comment by deatil** [comment]
> `http://admin.xiijq.cn/`,这个可以直接访问的，

编译后的base_url是stage-api吗？看起来就是这个配置有问题。前端打包部署可以先具体的看下 vue-element-admin 文档

**Comment by deatil** [comment]
env配置有三个，还有个staging的可以也改下，你打包的用的估计是这个env

**Comment by jinxu96** [comment]
`server
{
    listen 80;
    server_name admin.xiijq.cn;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/web-admin-mi-m/dist/;

    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #SSL-END

    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    #error_page 404 /404.html;
    #error_page 502 /502.html;
    
    # 默认访问前端项目
    location / {
        #解决页面刷新404问题
        try_files $uri $uri/ /index.html;
    }
    # 后端项目
    location ~* ^/(admin-api) {
        try_files $uri $uri/ /index.php?$query_string;
    }
    
    #ERROR-PAGE-END

    #PHP-INFO-START  PHP引用配置，可以注释或修改
    include enable-php-81.conf;
    location ~ \.php(.*)$
    {
        root  /www/wwwroot/api-admin-mi-m/public/;
        try_files $uri =404;
        fastcgi_pass  unix:/tmp/php-cgi-81.sock;
        fastcgi_index index.php;
        include fastcgi.conf;
        include pathinfo.conf;
    }
    #PHP-INFO-END

    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/admin.xiijq.cn.conf;
    #REWRITE-END

    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }

    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }

    #禁止在证书验证目录放入敏感文件
    if ( $uri ~ "^/\.well-known/.*\.(php|jsp|py|js|css|lua|ts|go|zip|tar\.gz|rar|7z|sql|bak)$" ) {
        return 403;
    }

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      30d;
        error_log /dev/null;
        access_log /dev/null;
    }

    location ~ .*\.(js|css)?$
    {
        expires      12h;
        error_log /dev/null;
        access_log /dev/null;
    }
    
    # 前端静态资源处理
    location  ^~ /images/ {
        alias /www/wwwroot/web-admin-mi-m/dist/images/;
    }

    # 后端静态资源处理
    location  ^~ /storage/ {
        alias /www/wwwroot/api-admin-mi-m/public/storage/;
    }
    access_log  /www/wwwlogs/admin.xiijq.cn.log;
    error_log  /www/wwwlogs/admin.xiijq.cn.error.log;
}
server {
  listen       9527;
  server_name  localhost;
  
  # 接口代理，用于解决跨域问题
  location /admin-api {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    
    # 后台接口地址
    proxy_pass http://127.0.0.1:9527/admin-api;
    # proxy_redirect default;
    # add_header Access-Control-Allow-Origin *;
    # add_header Access-Control-Allow-Headers X-Requested-With;
    # add_header Access-Control-Allow-Methods GET,POST,PUT,PATCH,DELETE,OPTIONS;
  }
}`

这是我宝塔的配置，前端可以访问，就是有关的接口404，我在本地nginx配置了，部署起来是没问题的，放到线上就不行了。。

**Comment by jinxu96** [comment]
`server
{
    listen 80;
    server_name admin.xiijq.cn;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/web-admin-mi-m/dist/;

    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #SSL-END

    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    #error_page 404 /404.html;
    #error_page 502 /502.html;
    
    # 默认访问前端项目
    location / {
        #解决页面刷新404问题
        try_files $uri $uri/ /index.html;
    }
    # 后端项目
    location ~* ^/(admin-api) {
        try_files $uri $uri/ /index.php?$query_string;
    }
    
    #ERROR-PAGE-END

    #PHP-INFO-START  PHP引用配置，可以注释或修改
    include enable-php-81.conf;
    location ~ \.php(.*)$
    {
        root  /www/wwwroot/api-admin-mi-m/public/;
        try_files $uri =404;
        fastcgi_pass  unix:/tmp/php-cgi-81.sock;
        fastcgi_index index.php;
        include fastcgi.conf;
        include pathinfo.conf;
    }
    #PHP-INFO-END

    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/admin.xiijq.cn.conf;
    #REWRITE-END

    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }

    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }

    #禁止在证书验证目录放入敏感文件
    if ( $uri ~ "^/\.well-known/.*\.(php|jsp|py|js|css|lua|ts|go|zip|tar\.gz|rar|7z|sql|bak)$" ) {
        return 403;
    }

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      30d;
        error_log /dev/null;
        access_log /dev/null;
    }

    location ~ .*\.(js|css)?$
    {
        expires      12h;
        error_log /dev/null;
        access_log /dev/null;
    }
    
    # 前端静态资源处理
    location  ^~ /images/ {
        alias /www/wwwroot/web-admin-mi-m/dist/images/;
    }

    # 后端静态资源处理
    location  ^~ /storage/ {
        alias /www/wwwroot/api-admin-mi-m/public/storage/;
    }
    access_log  /www/wwwlogs/admin.xiijq.cn.log;
    error_log  /www/wwwlogs/admin.xiijq.cn.error.log;
}
server {
  listen       9527;
  server_name  localhost;
  
  # 接口代理，用于解决跨域问题
  location /admin-api {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    
    # 后台接口地址
    proxy_pass http://127.0.0.1:9527/admin-api;
    # proxy_redirect default;
    # add_header Access-Control-Allow-Origin *;
    # add_header Access-Control-Allow-Headers X-Requested-With;
    # add_header Access-Control-Allow-Methods GET,POST,PUT,PATCH,DELETE,OPTIONS;
  }
}`

这是我宝塔的配置，前端可以访问，就是有关的接口404，我在本地nginx配置了，部署起来是没问题的，放到线上就不行了。。

**Comment by deatil** [comment]
404是nginx返回的还是php后端返回的

**Comment by jinxu96** [comment]
nginx，我拿着http://admin.xiijq.cn/admin-api/passport/captcha这个接口直接访问

**Comment by deatil** [comment]
> nginx，我拿着[http://admin.xiijq.cn/admin-api/passport/captcha这个接口直接访问](http://admin.xiijq.cn/admin-api/passport/captcha%E8%BF%99%E4%B8%AA%E6%8E%A5%E5%8F%A3%E7%9B%B4%E6%8E%A5%E8%AE%BF%E9%97%AE)

看不出来是哪的问题。你可以先看下nginx的日志和laravel的日志，然后单独的放一个php文件在前端目录看能不能访问

**Comment by jinxu96** [comment]
nginx和laravel没有错误日志，我在前端根目录放了php文件，能访问 http://admin.xiijq.cn](http://admin.xiijq.cn

**Comment by jinxu96** [comment]
> > nginx，我拿着[http://admin.xiijq.cn/admin-api/passport/captcha这个接口直接访问](http://admin.xiijq.cn/admin-api/passport/captcha%E8%BF%99%E4%B8%AA%E6%8E%A5%E5%8F%A3%E7%9B%B4%E6%8E%A5%E8%AE%BF%E9%97%AE)
> 
> 看不出来是哪的问题。你可以先看下nginx的日志和laravel的日志，然后单独的放一个php文件在前端目录看能不能访问

nginx和laravel没有错误日志，我在前端根目录放了php文件，能访问 http://admin.xiijq.cn

**Comment by deatil** [comment]
看起来像 include /www/server/panel/vhost/rewrite/admin.xiijq.cn.conf; 这个文件的没有改到，用的这个文件的路由

**Comment by jinxu96** [comment]
这个文件我看了，里面没有内容，这个文件也要配置什么东西吗？

**Comment by jinxu96** [comment]
> 这个文件我看了，里面没有内容，这个文件也要配置什么东西吗？

这个文件，好像是宝塔配置伪静态的

**Comment by deatil** [comment]
location ~ ^/(admin-api) {

这个你在根目录加了php后没有进到api接口，那可能就是配置有问题，需要根据nginx对应的版本修改下

**Comment by jinxu96** [comment]
人都麻了，搞了两天了

**Comment by jinxu96** [comment]
`    location / {
        alias /path/dist/;
        try_files $uri $uri/ /index.html;
    }`
这样写根本访问不到首页，css，js报404，只能拿出来root /path/dist/，怀疑好几个location都不生效

**Comment by deatil** [comment]
> ` location / { alias /path/dist/; try_files $uri $uri/ /index.html; }` 这样写根本访问不到首页，css，js报404，只能拿出来root /path/dist/，怀疑好几个location都不生效

这个需要根据nginx版本来适配更改，默认的只是适应一个大版本的nginx

**Comment by jinxu96** [comment]
我把服务器的nginx和本地的nginx版本换成一样的了，本地能访问，接口都没问题，就服务上的有问题

**Comment by deatil** [comment]
> 我把服务器的nginx和本地的nginx版本换成一样的了，本地能访问，接口都没问题，就服务上的有问题

查下 宝塔 部署laravel的文档

**Comment by jinxu96** [comment]
宝塔单独部署的话没问题，就是同域名部署前后端分离就出问题0.0

**Comment by jinxu96** [comment]
> > 我把服务器的nginx和本地的nginx版本换成一样的了，本地能访问，接口都没问题，就服务上的有问题
> 
> 查下 宝塔 部署laravel的文档

宝塔单独部署的话没问题，就是同域名部署前后端分离就出问题0.0

**Comment by deatil** [comment]
> > > 我把服务器的nginx和本地的nginx版本换成一样的了，本地能访问，接口都没问题，就服务上的有问题
> > 
> > 
> > 查下 宝塔 部署laravel的文档
> 
> 宝塔单独部署的话没问题，就是同域名部署前后端分离就出问题0.0

这个就只能自己再找下问题了
