### ISSUE TITLE
新建管理员提示没有权限

### ISSUE THREAD

**Issue by xiaogezzz** [deatil/larke-admin#3]
已经给了所有权限，登陆时依然显示没有权限
![image](https://user-images.githubusercontent.com/27753789/114005555-382c3300-9892-11eb-8026-d9d7cc04dfca.png)

![image](https://user-images.githubusercontent.com/27753789/114005420-19c63780-9892-11eb-8a1d-2febe772060b.png)

**Comment by deatil** [comment]
是登陆不上还是登陆上了进首页出现的提示？

**Comment by xiaogezzz** [comment]
> 是登陆不上还是登陆上了进首页出现的提示？

进不了首页，直接在登录页提示的，但是那个 login 接口是返回的登陆成功

**Comment by deatil** [comment]
> > 是登陆不上还是登陆上了进首页出现的提示？
> 
> 进不了首页，直接在登录页提示的，但是那个 login 接口是返回的登陆成功

你前端页面的包里的路由信息有导入进去吗？看起来像前端的权限路由信息没有导入？

**Comment by deatil** [comment]
就是 前端项目 里执行第三步那个你有执行吗？

**Comment by xiaogezzz** [comment]
```
php artisan larke-admin-frontend:import-menus --force
```
这个嘛，执行啦🤷‍♂️

**Comment by deatil** [comment]
> ```
> php artisan larke-admin-frontend:import-menus --force
> ```
> 
> 这个嘛，执行啦🤷‍♂️

我好像发现是哪的问题了

你再执行下这个命令
`php artisan larke-admin:import-route`
看有没有多出前端适配接口的权限路由，然后再执行下你发的这个命令

**Comment by xiaogezzz** [comment]
可以啦，感谢😄
