### ISSUE TITLE
[Question]: 我设置了软连接，但是上传图像得时候只有根目录下得storage有图片，public/storage下没有

### ISSUE THREAD

**Issue by jinxu96** [deatil/larke-admin#30]
### 疑惑的地方

我设置了软连接 php artisan storage:link，但是上传图像得时候只有根目录下得storage有图片，public/storage下没有，nginx配置了，访问得链接也不对 ，http://localhost/storage/images/3d638cd30bef0b52ab65ad1d215b3425.png，怎么是localhost

### 期望的结果

权限我也给了

**Comment by deatil** [comment]
需要在env里配置资源的域名，这个可以看laravel的文档

**Comment by jinxu96** [comment]
> 需要在env里配置资源的域名，这个可以看laravel的文档

是的是的，我本地都设置了的，刚想起来，妈的，宝塔的配置我终于弄好了，搞了3天，服了0.0

**Comment by deatil** [comment]
> > 需要在env里配置资源的域名，这个可以看laravel的文档
> 
> 是的是的，我本地都设置了的，刚想起来，妈的，宝塔的配置我终于弄好了，搞了3天，服了0.0

😂
