### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lhkkhl** [deatil/larke-admin#32]
### larke-admin 版本

1.7.0

### php 版本

8.2

### Laravel 版本

10

### 是否依旧存在

可以

### bug描述

![image](https://github.com/deatil/larke-admin/assets/30851098/9a83bc86-32dc-4244-a6c5-c983ac819697)

**Comment by deatil** [comment]
可以打开laravel的日志，看下日志具体的报错
