### ISSUE TITLE
[Question]: 请问支持postgresql 数据库吗？

### ISSUE THREAD

**Issue by Alvazz** [deatil/larke-admin#36]
### 疑惑的地方

刚刚接触，在read.me里面没有看到关于数据库的描述，所以请问一下，这个项目是否能够支持postgresql。谢谢

### 期望的结果

期待回答噢

**Comment by deatil** [comment]
orm 用的是 laravel 的 orm ，laravel 的 orm 支持 postgresql ，需要可以根据文档提示修改配置测试下
