### ISSUE TITLE
[Question]: 我根据流程走完了，也没报错，但是根本没有后台那些代码啊，我需要怎么个安装方法,laravel后台的api，麻烦大佬告知，谢谢

### ISSUE THREAD

**Issue by joseph-wsq** [deatil/larke-admin#37]
### 疑惑的地方

我根据流程走完了，也没报错，但是根本没有后台那些代码啊，我需要怎么个安装方法,laravel后台的api，麻烦大佬告知，谢谢

### 期望的结果

想要知道怎么安装，laravel的后台接口，我现在根据文档中的不通用，可以+v 1864065010  谢谢

**Comment by deatil** [comment]
安装后admin的代码在vendor文件夹里

**Comment by deatil** [comment]
api可以看文档 https://github.com/deatil/larke-admin/tree/main/docs/api
需要admin页面的需要下载前端的项目编译

**Comment by deatil** [comment]
如果要测试或者查看具体的接口，可以编译前端项目后查看

**Comment by joseph-wsq** [comment]
在vendor里面我怎么访问，怎么去二开呢？我前台编译好了，去访问是返回404的

**Comment by joseph-wsq** [comment]
> 如果要测试或者查看具体的接口，可以编译前端项目后查看


在vendor里面我怎么访问，怎么去二开呢？我前台编译好了，去访问是返回404的

**Comment by deatil** [comment]
前端编译前需要修改 https://github.com/deatil/larke-admin-frontend/blob/main/.env.development.larke#L5 后端的api地址再编译，如果没有不清楚的话可以看vue-element-admin的文档
二开的话，要看哪种了，只是加功能的话，推荐用插件来扩展功能
如果要改admin的核心代码，可以在vendor里直接改，不过推荐是提前引入要改的对应文件，作为覆盖方式二开，后期升级admin核心方便些

**Comment by deatil** [comment]
api的部分文档可以看这个 https://github.com/deatil/larke-admin/tree/main/docs/api

**Comment by deatil** [comment]
后端的api地址需要是你测试的地址
