### ISSUE TITLE
安装配置好以后,可以正常登录,但是不能修改数据一直提示Request failed with status code 405

### ISSUE THREAD

**Issue by 331164885** [deatil/larke-admin#4]
后台里的信息获取都正常,但就是不能提交表单. 
![Screenshot from 2021-05-08 16-05-29](https://user-images.githubusercontent.com/8360812/117531879-5adb7400-b017-11eb-91d0-84ae6cefde4c.png)

**Comment by deatil** [comment]
laravel有没有什么报错信息？

**Comment by deatil** [comment]
本地测试了下，没有出现截图的问题。有可能是你的nginx或者apache的转发问题或者浏览器的插件问题什么的，你可以查找下看看
