### ISSUE TITLE
请问按步骤装完后访问还是laravel的页面

### ISSUE THREAD

**Issue by rockmelodies** [deatil/larke-admin#5]
![image](https://user-images.githubusercontent.com/24653177/118913044-4ffbda00-b95b-11eb-88ea-141409c4a878.png)

**Comment by deatil** [comment]
需要前端配合。文档里跳转到前端的项目页面，按文档把前端编译出来

**Comment by deatil** [comment]
https://github.com/deatil/larke-admin-frontend
需要这个配合

**Comment by rockmelodies** [comment]
安装完成之后还是不行

**Comment by rockmelodies** [comment]
有没有更详细的步骤 是不是需要cnpm install 和 cnpm run dev

**Comment by deatil** [comment]
> 有没有更详细的步骤 是不是需要cnpm install 和 cnpm run dev

详细步骤？嗯，项目是分了后端项目和前端项目的。npm这个是需要的，前端项目安装完后，前端文件是复制到了public/admin里面，然后就需要根据vue-element-admin的文档来编译

**Comment by deatil** [comment]
可以查看前端编译文档 

public/admin/README.zh-CN.md
