### ISSUE TITLE
只能使用Composer进行扩展吗？

### ISSUE THREAD

**Issue by hitaian** [deatil/larke-admin#7]
RT

**Comment by deatil** [comment]
不是。
你可以上传扩展试下，确认下上传后的扩展位置。
扩展是可以直接放扩展目录安装的

**Comment by deatil** [comment]
我上面说的是系统自带的扩展功能。你说的扩展是哪种？

**Comment by hitaian** [comment]
我想说如果基于这套系统做二次开发的话，怎么写比较好呢。

**Comment by deatil** [comment]
> 我想说如果基于这套系统做二次开发的话，怎么写比较好呢。

得看项目的想怎么样来开发。系统没有去怎么限制laravel自带的app开发方式。
系统的话，为了升级方便，拆分方便，推荐用扩展方式比较好。
如果喜欢纯的laravel开发的话，建议还是代码在app目录开发好些
