### ISSUE TITLE
域名设置cdn，每次登录都是提示token已过期

### ISSUE THREAD

**Issue by doudou-dream** [deatil/larke-admin#9]
域名设置cdn，每次登录都是提示token已过期

**Comment by deatil** [comment]
有截图吗？是登陆提交成功后进首页提示吗？

**Comment by deatil** [comment]
后端的api也做了cdn处理吗？

**Comment by doudou-dream** [comment]
登录成功后再获取路由提示token过期，api没有处理，请问怎么处理api呀；我看了一下是jwt中sub信息不一样

**Comment by deatil** [comment]
> 登录成功后再获取路由提示token过期，api没有处理，请问怎么处理api呀；我看了一下是jwt中sub信息不一样

你本地有测试吗？本地测试下有没有问题？没问题的话，那就可能需要nginx这些把ip和ua转发到php

**Comment by doudou-dream** [comment]
> > 登录成功后再获取路由提示token过期，api没有处理，请问怎么处理api呀；我看了一下是jwt中sub信息不一样
> 
> 
> 
> 你本地有测试吗？本地测试下有没有问题？没问题的话，那就可能需要nginx这些把ip和ua转发到php

本地测试登录是正常的，用ip加端口也可以正常访问；不会设置nginx，有教程链接发我一下呗，谢谢啦
